class CreateIndividuals < ActiveRecord::Migration[5.2]
  def change
    create_table :individuals do |t|
      t.string :cantville
      t.string :nummi
      t.string :achlr
      t.string :aemmr
      t.integer :aged
      t.string :ager20
      t.integer :agerev
      t.string :agerevq
      t.integer :anai
      t.string :anemr
      t.string :apaf
      t.string :arm
      t.string :ascen
      t.string :bain
      t.string :bati
      t.string :catiris
      t.string :catl
      t.string :catpc
      t.string :chau
      t.string :chfl
      t.string :chos
      t.string :clim
      t.string :cmbl
      t.string :couple
      t.integer :cs1
      t.string :cuis
      t.string :dept
      t.string :derou
      t.string :dipl_15
      t.string :dnai
      t.string :eau
      t.string :egoul
      t.string :elec
      t.string :empl
      t.string :etud
      t.string :garl
      t.string :hlml
      t.string :iletud
      t.string :ilt
      t.string :immi
      t.string :inai
      t.string :inatc
      t.string :infam
      t.string :inper
      t.string :inperf
      t.decimal :ipondi
      t.string :iran
      t.string :iris
      t.string :lienf
      t.string :lprf
      t.string :lprm
      t.string :metrodom
      t.string :moco
      t.string :modv
      t.string :na17
      t.string :na5
      t.string :naidt
      t.string :nbpi
      t.string :ne17fr
      t.string :ne24fr
      t.string :ne3fr
      t.string :ne5fr
      t.string :nenfr
      t.string :nperr
      t.string :numf
      t.string :oridt
      t.string :rech
      t.string :region
      t.string :sani
      t.string :sanidom
      t.string :sexe
      t.string :sfm
      t.string :stat_conj
      t.string :statr
      t.string :stocd
      t.string :surf
      t.string :tact
      t.string :tactd16
      t.string :tp
      t.string :trans
      t.string :triris
      t.string :typc
      t.string :typfc
      t.string :typl
      t.string :typmc
      t.string :typmr
      t.string :voit
      t.string :wc
    end
  end
end
